"""create rooms and schedules

Revision ID: d4d7a9ec6296
Revises: 
Create Date: 2026-02-03 03:32:17.150862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4d7a9ec6296'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('parent', sa.String(length=60), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('start', sa.String(length=10), nullable=False),
    sa.Column('end', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=False),
    sa.Column('teacher', sa.String(length=60), nullable=False),
    sa.Column('room_tag', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['room_tag'], ['rooms.tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    op.drop_table('rooms')
    # ### end Alembic commands ###
